YangGuangTongXing/YangGuangTongXing/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YangGuangTongXing;

namespace YangGuangTongXing.Controllers
{
    public class AnnouncementController : Controller
    {
        private YangGuangTongXingEntities db = new YangGuangTongXingEntities();

        //
        // GET: /Announcement/

        public ViewResult Index()
        {
            var announcements = db.Announcements.Include(a => a.UpdatedUser);
            return View(announcements.ToList());
        }

        //
        // GET: /Announcement/Details/5

        public ViewResult Details(int id)
        {
            Announcement announcement = db.Announcements.Find(id);
            return View(announcement);
        }

        //
        // GET: /Announcement/Create

        public ActionResult Create()
        {
            ViewBag.UpdatedBy = new SelectList(db.Users, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Announcement/Create

        [HttpPost]
        public ActionResult Create(Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                db.Announcements.Add(announcement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UpdatedBy = new SelectList(db.Users, "UserId", "UserName", announcement.UpdatedBy);
            return View(announcement);
        }

        //
        // GET: /Announcement/Edit/5

        [Authorize(Roles = "editor")]
        public ActionResult Edit(int id)
        {
            Announcement announcement = db.Announcements.Find(id);
            ViewBag.UpdatedBy = new SelectList(db.Users, "UserId", "UserName", announcement.UpdatedBy);
            return View(announcement);
        }

        //
        // POST: /Announcement/Edit/5

        [HttpPost]
        public ActionResult Edit(Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(announcement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UpdatedBy = new SelectList(db.Users, "UserId", "UserName", announcement.UpdatedBy);
            return View(announcement);
        }

        [Authorize(Roles = "editor")]
        [HttpPost]
        public bool SaveAnnouncement(int id, string content)
        {
            Announcement announcement = db.Announcements.Find(id);
            announcement.Content = HttpUtility.UrlDecode(content);
            string userName = User.Identity.Name;
            announcement.UpdatedUser = db.Users.SingleOrDefault(u => u.UserName == userName);
            try
            {
                db.Entry(announcement).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception)
            {
                return false;
            } 
            return true;
        }



        //
        // GET: /Announcement/Delete/5

        public ActionResult Delete(int id)
        {
            Announcement announcement = db.Announcements.Find(id);
            return View(announcement);
        }

        //
        // POST: /Announcement/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Announcement announcement = db.Announcements.Find(id);
            db.Announcements.Remove(announcement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

YangGuangTongXing/YangGuangTongXing/Controllers/ContributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace YangGuangTongXing.Controllers
{
    public class ContributeController : Controller
    {
        //
        // GET: /Contribute/
        YangGuangTongXingEntities db = new YangGuangTongXingEntities();

        public ActionResult Index()
        {
            Announcement ann = db.Announcements.Where(a => a.Remark.Contains("捐助流程")).FirstOrDefault();
            return View(ann);
        }

    }
}

YangGuangTongXing/YangGuangTongXing/Views/Contribute/Index.cshtml
@model YangGuangTongXing.Announcement
@{
    ViewBag.Title = "Index";
}

<div>
    <div class="pane-left-common">
        <div>
            <div class="btn-group-vertical">
                <button type="button" class="btn btn-default">Button</button>
                <button type="button" class="btn btn-default">Button</button>
                <div class="btn-group">
                    <button id="btnGroupVerticalDrop1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Dropdown
          <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop1">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
                <button type="button" class="btn btn-default">Button</button>
                <button type="button" class="btn btn-default">Button</button>
                <div class="btn-group">
                    <button id="btnGroupVerticalDrop2" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Dropdown
          <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop2">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
                <div class="btn-group">
                    <button id="btnGroupVerticalDrop3" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Dropdown
          <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop3">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
                <div class="btn-group">
                    <button id="btnGroupVerticalDrop4" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Dropdown
          <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="btnGroupVerticalDrop4">
                        <li><a href="#">Dropdown link</a></li>
                        <li><a href="#">Dropdown link</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pane-right-common">
        @{
            HtmlString content = new HtmlString(Model.Content);
        }
        @content
    </div>
</div>
<p>
    @if (User.IsInRole("editor"))
    {
        @Html.ActionLink("编辑", "Edit", "Announcement", new { id = Model.AnnouncementId }, null)
    }
</p>